export const topics = {
  General: [
    "Pizza",
    "Beach",
    "Library",
    "Hospital",
    "Soccer",
    "Guitar",
    "Coffee",
    "Rainbow",
    "Airport",
    "Movie Theater",
    "Camping",
    "Snowman",
    "Robot",
    "Subway",
    "Chocolate",
    "Fireworks",
    "Museum",
    "Sushi"
  ],
  Family: [
    "Playground",
    "Birthday Cake",
    "Swimming Pool",
    "Dinosaur",
    "Ice Cream",
    "Treehouse",
    "Pajamas",
    "Board Game",
    "Zoo",
    "School Bus",
    "Pancakes",
    "Kite",
    "Bicycle",
    "Storybook",
    "Lemonade",
    "Puppet Show",
    "Treasure Map",
    "Bubble Bath"
  ],
  Adult: [
    "Casino",
    "Wine Bar",
    "Gym",
    "Office",
    "Nightclub",
    "Rooftop",
    "Conference",
    "Spa",
    "Mortgage",
    "Taxi",
    "Cocktail",
    "Karaoke",
    "First Date",
    "Hotel Lobby",
    "Paycheck",
    "Yoga Studio",
    "Dinner Party",
    "Airport Lounge"
  ]
};

export const categories = Object.keys(topics);
